services:
  postgres:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - $DATABASE_PORT:5432
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD

  redis:
    image: redis:latest
    ports:
      - $REDIS_PORT:6379

volumes:
  postgres: